export const DAILY_VAULT_QUESTIONS = [
  "If your sweat today was a perfume, what would it be called?",
  "Which muscle is currently yelling the loudest at you?",
  "What's the 'Main Character' song of your outdoor workout today?",
  "If you had to explain today's reading to a golden retriever, what would you say?",
  "What's one sentence you read today that changed your brain chemistry?",
  "Is your brain currently a 'Zettelkasten' or a 'junk drawer'?",
  "What did the host family serve that Gael definitely wouldn't have eaten?",
  "If you could trade your gallon of water for one local snack right now, what is it?",
  "Rate today's 'Vibe' from 1 (Cold Shower) to 10 (Fresh Byrek).",
  "If you were a medieval blacksmith, what weapon did you forge during today's workout?",
  "Which page of today's reading made you want to argue with the author?",
  "What percentage of today's water intake was purely out of spite?",
  "If your grit had a physical texture today, what would it feel like?",
  "What excuse did your brain offer you today, and how did you tell it to shut up?",
  "Did you feel more like a philosopher or a gladiator today?",
  "If today's diet was a geometric shape, how perfectly symmetric was it?",
  "Describe the exact moment today when you wanted to quit but didn't.",
  "Which local Albanian phrase perfectly summarizes your energy levels today?",
  "Did your outdoor workout feel like an epic quest or a forced march?",
  "What's the most profound thought you had while blindly forcing down water?",
  "If someone narrated your indoor workout like a nature documentary, what would they say?",
  "What's one idea from today's reading that you're going to steal and use as your own?",
  "How many times did you mentally negotiate with the universe during your second workout?",
  "If the challenge ended tomorrow, what habit from today would you keep forever?",
  "Rate your discipline today as a weather forecast.",
  "What was the biggest distraction you absolutely ghosted today?",
  "Did you conquer the day, or did you survive it?",
  "What Albanian landscape does your current mental state resemble?",
  "If your muscles could write a review of today’s workout, how many stars would they give?",
  "What's a concept from your reading that makes the pain of the physical workouts worth it?",
  "Describe the taste of your last ounce of water today.",
  "If your progress photo today were an album cover, what would the album be called?",
  "How much of today's success was mechanical routine vs raw willpower?",
  "What's the most surprising thing you learned about your own patience today?",
  "If there was a 'villain' in today's story, what was it?",
  "Which part of your body is most offended by your life choices right now?",
  "What quote from today's reading should be spray-painted on a brick wall?",
  "Did today feel like a montage sequence or a slow-motion dramatic scene?",
  "What's one local Albanian habit you completely avoided to maintain your diet today?",
  "If today's effort was cryptocurrency, would you invest in it?",
  "How many times did you check the clock during the last 10 minutes of your workout?",
  "What's an absolute lie your brain tried to tell you about your daily reading?",
  "How would you explain your water vessel to a confused time traveler?",
  "What's the most stoic moment you had today?",
  "If today’s discipline was a flavor, is it spicy, bitter, or completely tasteless?",
  "What's a minor inconvenience that almost derailed you, and why didn't it?",
  "Did your mindset improve or deteriorate during your outdoor session?",
  "If your daily Vault reflection was a tweet, what's a drafted one you deleted?",
  "What physical sensation are you most proud of achieving today?",
  "How did today's reading mentally prepare you for tomorrow's suffering?",
  "If you had to pay $1 for every time you groaned today, how broke are you?",
  "What completely silent victory did you have today that nobody else noticed?",
  "Rate the \"main character energy\" of your diet today.",
  "Is your hydration level currently \"desert oasis\" or \"corporate water cooler\"?",
  "What's the most intense look someone gave you while you were doing your outdoor workout?",
  "If you could fast-forward through one part of today’s checklist, what would it be?",
  "What's a profound realization you had while simply doing the work?",
  "Did you feel more like a student or a master today?",
  "If your inner dialogue today was a podcast, would anyone subscribe?",
  "What's the most difficult page you read today, not because of the words, but the truth?",
  "How many times today did you remind yourself why you started?",
  "What's a local temptation you walked past today without a second glance?",
  "If your discipline today was a piece of architecture, what kind of building is it?",
  "What's the biggest difference between your Day 1 mindset and today's mindset?",
  "Did the weather cooperate, or was it a paid actor sent to ruin your outdoor workout?",
  "How many times did you feel completely ridiculous but did it anyway?",
  "What's one thing you read today that you instantly wanted to tell Gael?",
  "If today's 75 Hard effort was a movie genre, what is it?",
  "What's the most robotic, automated action you took today?",
  "How did you turn a moment of weakness into a moment of strength today?",
  "If you could rate the aesthetic of today's progress photo out of 10?",
  "What's one mental hurdle you cleared today that would have stopped you a month ago?",
  "Did you use anger, calm, or pure stubbornness as fuel today?",
  "What's the most \"Shëngjin\" thing that happened to you today while grinding?",
  "If you had to write a thesis based on today's reading, what's the title?",
  "How did you trick yourself into finishing your last quart of water?",
  "What's a completely mundane moment today that felt surprisingly epic?",
  "If your outdoor workout had a final boss, what was it?",
  "How many times did you question the concept of 'optional' today?",
  "What's the most valuable lesson today's physical pain taught you?",
  "If your diet plan was a high-end restaurant menu, what would today be called?",
  "What concept from your book made you stare blankly at a wall for five minutes?",
  "Did you feel more aligned with your mind or your body today?",
  "What's the most unglamorous part of today that you secretly loved?",
  "If today was a test, what grade would you give your execution?",
  "How did today's grind separate you from the person you used to be?",
  "What's a fleeting thought you had during your indoor workout that you want to remember?",
  "If you had to summarize today's discipline in three words, what are they?",
  "What's the biggest physical comfort you willingly sacrificed today?",
  "How did the reading fundamentally shift your perspective on your current challenge?",
  "If your willpower today was a battery, what percentage is it at right now?",
  "What's a local Albanian custom you participated in safely today without breaking the rules?",
  "Did you execute today out of passion or pure, cold logic?",
  "What's the most poetic way you can describe your post-workout exhaustion?",
  "If your daily grind was an art exhibit, what would the critics say?",
  "How many times did you mentally redesign your life during today's reading?",
  "What's the one task today that required zero motivation because it's just who you are now?",
  "If you could bottle the peace you feel right now, what would you call it?",
  "What's the most significant micro-decision you made today that kept you on the path?",
  "How much more dangerous is your mindset today than it was yesterday?"
];
